### ISSUE TITLE
Username links on some extension pages don't work

### ISSUE THREAD

**Issue by Galixte** [tas2580/userinfo#2]
Hi @tas2580,

when your extension is activated, on some extension pages the username links don't work.

By example this issue opened explain the problem with LiveSearch extension by @alg5: https://github.com/alg5/liveSearch/issues/13, especially this post explains: https://github.com/alg5/liveSearch/issues/13#issuecomment-133677806.

Other extensions which have the problem with your extension:
- https://github.com/rxu/thanks_for_posts by @rxu,
- https://github.com/david63/david63-userranks by @david63 (See the same problem explanation: https://github.com/david63/david63-userranks/issues/6).

Maybe others extensions have this problem…

Otherwise, In ACP without any extensions activated, except yours, all links to usernames are broken.

If i disable your extension everything works fine for the username links.

**Comment by Galixte** [comment]
Hi @tas2580,

could you take a look.

**Comment by Galixte** [comment]
Hi @tas2580,

could you take a look, please ?

**Comment by david63** [comment]
@Galixte 

I cannot see any problems with my User Ranks ext

**Comment by Galixte** [comment]
Yes, i’m sure it’s the userinfo extension which has a problem.

**Comment by Galixte** [comment]
@tas2580, please this issue is too important to leave this unsolved.

**Comment by tas2580** [comment]
I hope this patch will fix the problem

**Comment by Galixte** [comment]
Thanks i will test.
